<?php

namespace FedexRest\Tests\AddressValidation;

use FedexRest\Authorization\Authorize;
use FedexRest\Entity\Address;
use FedexRest\Exceptions\MissingAccessTokenException;
use FedexRest\Exceptions\MissingAuthCredentialsException;
use FedexRest\Services\AddressValidation\AddressValidation;
use FedexRest\Tests\BaseTestCase;
use GuzzleHttp\Exception\GuzzleException;

class AddressValidationTest extends BaseTestCase
{
    protected Authorize $auth;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setupAuth();
    }

    /**
     * @throws MissingAccessTokenException
     * @throws MissingAuthCredentialsException
     * @throws GuzzleException
     */
    public function testValidateAddress()
    {
        $test = (new AddressValidation())
            ->setAddress(
                (new Address())
                    ->setCity('Irving')
                    ->setCountryCode('US')
                    ->setStateOrProvince('TX')
                    ->setPostalCode('75063-8659')
                    ->setStreetLines('7372 PARKRIDGE BLVD', 'APT 286', '2903 sprank')
            )
            ->setAccessToken($this->auth->authorize()->access_token)
            ->request();
        $this->assertObjectHasProperty('transactionId', $test);
    }
}
